### ISSUE TITLE
Add ChryzHub Blogs 

### ISSUE THREAD

**Issue by chryzcode** [chryz-hub/connect#20]
Add the ChryzHub Blog Site to the site

Here is the link https://chryzhub-blogs.herokuapp.com/

Use this Google icon `<span class="material-icons">
rss_feed
</span>`

**Comment by RajshreeVats** [comment]
new to open source. can I be assigned to this issue?

**Comment by chryzcode** [comment]
Go ahead, @RajshreeVats. If you have any challenges, please feel free to ask.

**Comment by RajshreeVats** [comment]
Great, Thanks!!
