### ISSUE TITLE
Set dark/light mode based on user/browser preferences

### ISSUE THREAD

**Issue by schmelto** [chryz-hub/connect#9]
you can see an implementation of this here https://github.com/DenverCoder1/github-readme-streak-stats/pull/91/files

**Comment by chryzcode** [comment]
Ok , thanks but I think other frontend developers would work on this cause I'm yet to know Javascript.

**Comment by jomefavourite** [comment]
> you can see an implementation of this here https://github.com/DenverCoder1/github-readme-streak-stats/pull/91/files

Okay, thanks @schmelto I'll be working on it very soon

**Comment by jomefavourite** [comment]
So can I close the issue?

**Comment by schmelto** [comment]
I would also add a listener on how the preference is set in the browser

```
window.matchMedia("(prefers-color-scheme: dark)").matches == true
```

**Comment by jomefavourite** [comment]
> I would also add a listener on how the preference is set in the browser
> 
> ```
> window.matchMedia("(prefers-color-scheme: dark)").matches == true
> ```

okay, I'll do that soon

**Comment by chryzcode** [comment]
@namangupta1399 @jomefavourite @Evavic44 please review this

**Comment by namangupta1399** [comment]
Update done by @ManuSquall . Closing the issue

**Comment by chryzcode** [comment]
Ok thanks guys
